
passed dict emned path ./dictionary_learning/dictionaries/pythia-70m-deduped/embed
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
  0%|                                               | 0/282 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/atticus/maheep/SAE_vs_DAS/main.py", line 300, in <module>
    train(DEVICE=args.device,
  File "/home/atticus/maheep/SAE_vs_DAS/main.py", line 82, in train
    logits = new_model(text, temperature=temprature)
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/atticus/maheep/SAE_vs_DAS/model.py", line 128, in forward
    l4_mask_sigmoid = t.sigmoid(self.l4_mask / temperature)
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'my_model' object has no attribute 'l4_mask'
Traceback (most recent call last):
  File "/home/atticus/maheep/SAE_vs_DAS/main.py", line 300, in <module>
    train(DEVICE=args.device,
  File "/home/atticus/maheep/SAE_vs_DAS/main.py", line 82, in train
    logits = new_model(text, temperature=temprature)
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/atticus/maheep/SAE_vs_DAS/model.py", line 128, in forward
    l4_mask_sigmoid = t.sigmoid(self.l4_mask / temperature)
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'my_model' object has no attribute 'l4_mask'