2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Configure stats pid to 32531
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_164405-vlovx92p/logs/debug.log
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_164405-vlovx92p/logs/debug-internal.log
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x17ca83ef0>
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_init.py:init():560] calling init triggers
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_init.py:init():610] starting backend
2024-05-22 16:44:05,816 INFO    MainThread:32531 [wandb_init.py:init():614] setting up manager
2024-05-22 16:44:05,817 INFO    MainThread:32531 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-22 16:44:05,818 INFO    MainThread:32531 [wandb_init.py:init():622] backend started and connected
2024-05-22 16:44:05,821 INFO    MainThread:32531 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-22 16:44:05,821 INFO    MainThread:32531 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-22 16:44:05,821 INFO    MainThread:32531 [wandb_init.py:init():711] updated telemetry
2024-05-22 16:44:05,849 INFO    MainThread:32531 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-22 16:44:06,545 INFO    MainThread:32531 [wandb_run.py:_on_init():2396] communicating current version
2024-05-22 16:44:06,628 INFO    MainThread:32531 [wandb_run.py:_on_init():2405] got version response 
2024-05-22 16:44:06,629 INFO    MainThread:32531 [wandb_init.py:init():795] starting run threads in backend
2024-05-22 16:44:10,732 WARNING MainThread:32531 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-05-22 16:44:44,050 INFO    MainThread:32531 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Configure stats pid to 32531
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_164444-4u5bx9s1/logs/debug.log
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_164444-4u5bx9s1/logs/debug-internal.log
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_init.py:init():560] calling init triggers
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_init.py:init():610] starting backend
2024-05-22 16:44:44,055 INFO    MainThread:32531 [wandb_init.py:init():614] setting up manager
2024-05-22 16:44:44,056 INFO    MainThread:32531 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-22 16:44:44,056 INFO    MainThread:32531 [wandb_init.py:init():622] backend started and connected
2024-05-22 16:44:44,059 INFO    MainThread:32531 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-22 16:44:44,059 INFO    MainThread:32531 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-22 16:44:44,059 INFO    MainThread:32531 [wandb_init.py:init():711] updated telemetry
2024-05-22 16:44:44,073 INFO    MainThread:32531 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-22 16:46:14,446 ERROR   MainThread:32531 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-22 16:46:14,447 ERROR   MainThread:32531 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-22 16:46:24,003 INFO    MainThread:32531 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-22 16:46:24,008 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Configure stats pid to 32531
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_164624-wt5e4rqe/logs/debug.log
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_164624-wt5e4rqe/logs/debug-internal.log
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_init.py:init():560] calling init triggers
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_init.py:init():610] starting backend
2024-05-22 16:46:24,009 INFO    MainThread:32531 [wandb_init.py:init():614] setting up manager
2024-05-22 16:46:24,010 INFO    MainThread:32531 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-22 16:46:24,010 INFO    MainThread:32531 [wandb_init.py:init():622] backend started and connected
2024-05-22 16:46:24,011 INFO    MainThread:32531 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-22 16:46:24,011 INFO    MainThread:32531 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-22 16:46:24,011 INFO    MainThread:32531 [wandb_init.py:init():711] updated telemetry
2024-05-22 16:46:24,027 INFO    MainThread:32531 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-22 16:47:54,724 ERROR   MainThread:32531 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-05-22 16:47:54,932 ERROR   MainThread:32531 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/maheepchaudhary/miniforge3/envs/nnsight/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
